Repository koseven/koseven, pull requests merged in 2018-12, with the labels that each got.

#295 Unittests on Windows Systems
  modules/userguide/tests/userguide/ControllerTest.php
  system/tests/kohana/DebugTest.php
  system/tests/kohana/LogTest.php
  system/tests/kohana/NumTest.php
  system/tests/kohana/UploadTest.php
Labels: bug

#208 halt script execution when exception occurs in view rendering
  system/classes/Kohana/View.php
Labels: bug, enhancement

#298 Travis CI Configuration Update
  .travis.yml
Labels: enhancement

#291 Redis
  modules/cache/classes/Cache/Redis.php
  modules/cache/classes/Kohana/Cache/Redis.php
  modules/cache/config/cache.php
  modules/cache/tests/cache/CacheBasicMethodsTest.php
  modules/cache/tests/cache/CacheTest.php
  modules/cache/tests/cache/RedisTest.php
  system/classes/Kohana/Core.php
  system/tests/kohana/RouteTest.php
Labels: enhancement
